#!/bin/bash

# Script to link codebase to Supabase
# Supports both local (Docker) and cloud Supabase instances

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}╔════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║     Supabase Connection Setup                          ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════╝${NC}"
echo ""

# Check if .env.local exists
ENV_FILE=".env.local"
if [ -f "$ENV_FILE" ]; then
    echo -e "${YELLOW}⚠️  .env.local already exists${NC}"
    read -p "Do you want to overwrite it? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo -e "${YELLOW}Skipping .env.local creation${NC}"
        exit 0
    fi
fi

# Ask user for Supabase type
echo -e "${BLUE}Select your Supabase setup:${NC}"
echo "1) Local Supabase (Docker) - Recommended for development"
echo "2) Cloud Supabase (Production/Staging)"
read -p "Enter choice [1-2]: " -n 1 -r
echo ""

if [[ $REPLY =~ ^[1]$ ]]; then
    # Local Supabase setup
    echo -e "${GREEN}Setting up for Local Supabase...${NC}"
    
    # Check if Supabase CLI is installed
    if ! command -v supabase &> /dev/null; then
        echo -e "${RED}❌ Supabase CLI is not installed${NC}"
        echo "Install it with: brew install supabase/tap/supabase"
        exit 1
    fi
    
    # Check if Docker is running
    if ! docker info &> /dev/null; then
        echo -e "${RED}❌ Docker is not running${NC}"
        echo "Please start Docker Desktop and try again"
        exit 1
    fi
    
    # Start Supabase if not running
    echo -e "${BLUE}Checking Supabase status...${NC}"
    if ! supabase status &> /dev/null; then
        echo -e "${YELLOW}Starting Supabase...${NC}"
        supabase start
    else
        echo -e "${GREEN}✓ Supabase is already running${NC}"
    fi
    
    # Get Supabase credentials
    echo -e "${BLUE}Fetching Supabase credentials...${NC}"
    SUPABASE_URL=$(supabase status --output json 2>/dev/null | grep -o '"API URL":"[^"]*' | cut -d'"' -f4 || echo "http://localhost:54321")
    ANON_KEY=$(supabase status --output json 2>/dev/null | grep -o '"anon key":"[^"]*' | cut -d'"' -f4 || echo "")
    SERVICE_KEY=$(supabase status --output json 2>/dev/null | grep -o '"service_role key":"[^"]*' | cut -d'"' -f4 || echo "")
    
    if [ -z "$ANON_KEY" ] || [ -z "$SERVICE_KEY" ]; then
        echo -e "${YELLOW}⚠️  Could not auto-detect keys. Please run 'supabase status' and enter manually:${NC}"
        read -p "Supabase URL [http://localhost:54321]: " SUPABASE_URL
        SUPABASE_URL=${SUPABASE_URL:-http://localhost:54321}
        read -p "Anon Key: " ANON_KEY
        read -p "Service Role Key: " SERVICE_KEY
    fi
    
    # Create .env.local
    cat > "$ENV_FILE" << EOF
# Supabase Configuration - Local Development
# Generated by link-supabase.sh on $(date)

# Supabase Local Instance
NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_KEY}

# API Server Configuration
SUPABASE_URL=${SUPABASE_URL}
SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_KEY=${SERVICE_KEY}

# Database Direct Connection (optional)
# DATABASE_URL=postgresql://postgres:postgres@localhost:54322/postgres
EOF

    echo -e "${GREEN}✓ Created .env.local with local Supabase credentials${NC}"
    echo ""
    echo -e "${BLUE}Supabase Studio: http://localhost:54323${NC}"
    echo -e "${BLUE}API URL: ${SUPABASE_URL}${NC}"
    
elif [[ $REPLY =~ ^[2]$ ]]; then
    # Cloud Supabase setup
    echo -e "${GREEN}Setting up for Cloud Supabase...${NC}"
    echo ""
    echo "Get your credentials from: https://app.supabase.com/project/_/settings/api"
    echo ""
    
    read -p "Supabase Project URL (e.g., https://xxxxx.supabase.co): " SUPABASE_URL
    read -p "Anon/Public Key: " ANON_KEY
    read -p "Service Role Key (keep this secret!): " SERVICE_KEY
    
    # Create .env.local
    cat > "$ENV_FILE" << EOF
# Supabase Configuration - Cloud/Production
# Generated by link-supabase.sh on $(date)

# Supabase Cloud Instance
NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_KEY}

# API Server Configuration
SUPABASE_URL=${SUPABASE_URL}
SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_KEY=${SERVICE_KEY}
EOF

    echo -e "${GREEN}✓ Created .env.local with cloud Supabase credentials${NC}"
    
else
    echo -e "${RED}Invalid choice${NC}"
    exit 1
fi

echo ""
echo -e "${BLUE}╔════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║     Next Steps                                         ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${YELLOW}1. Run database migrations:${NC}"
if [[ $REPLY =~ ^[1]$ ]]; then
    echo "   Migrations run automatically with 'supabase start'"
    echo "   Or manually: supabase db reset"
else
    echo "   Go to your Supabase dashboard → SQL Editor"
    echo "   Run migrations from: supabase/migrations/"
fi
echo ""
echo -e "${YELLOW}2. Verify connection:${NC}"
echo "   npm run dev"
echo "   Visit: http://localhost:3000/saas/dashboard"
echo ""
echo -e "${YELLOW}3. Check connection status:${NC}"
echo "   The dashboard will show Supabase connection status"
echo ""
echo -e "${GREEN}✓ Setup complete!${NC}"


