#!/bin/bash

# Script to link codebase to Supabase Cloud using Supabase CLI
# This sets up the connection and runs migrations

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}╔════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║     Supabase Cloud Setup (CLI)                        ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════╝${NC}"
echo ""

# Check if Supabase CLI is installed
if ! command -v supabase &> /dev/null; then
    echo -e "${RED}❌ Supabase CLI is not installed${NC}"
    echo ""
    echo "Install it with:"
    echo "  macOS: brew install supabase/tap/supabase"
    echo "  Linux: npm install -g supabase"
    echo "  Windows: npm install -g supabase"
    exit 1
fi

echo -e "${GREEN}✓ Supabase CLI is installed${NC}"
echo ""

# Check if already linked
if [ -f ".supabase/config.toml" ] && grep -q "project_id" .supabase/config.toml 2>/dev/null; then
    echo -e "${YELLOW}⚠️  Project appears to be linked to Supabase${NC}"
    read -p "Do you want to link to a different project? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo -e "${YELLOW}Skipping link step${NC}"
        SKIP_LINK=true
    fi
fi

# Login to Supabase if not already logged in
echo -e "${BLUE}Checking Supabase authentication...${NC}"
if ! supabase projects list &> /dev/null; then
    echo -e "${YELLOW}You need to login to Supabase${NC}"
    echo "Opening browser for authentication..."
    supabase login
else
    echo -e "${GREEN}✓ Already authenticated${NC}"
fi

echo ""

# Link to Supabase project
if [ "$SKIP_LINK" != "true" ]; then
    echo -e "${BLUE}Linking to Supabase project...${NC}"
    echo ""
    echo "You can find your project reference ID in your Supabase dashboard:"
    echo "https://app.supabase.com → Select Project → Settings → General"
    echo ""
    read -p "Enter your Supabase project reference ID: " PROJECT_REF
    
    if [ -z "$PROJECT_REF" ]; then
        echo -e "${RED}❌ Project reference ID is required${NC}"
        exit 1
    fi
    
    echo ""
    echo -e "${BLUE}Linking project...${NC}"
    supabase link --project-ref "$PROJECT_REF"
    
    if [ $? -eq 0 ]; then
        echo -e "${GREEN}✓ Successfully linked to Supabase project${NC}"
    else
        echo -e "${RED}❌ Failed to link project${NC}"
        exit 1
    fi
fi

echo ""

# Pull environment variables
echo -e "${BLUE}Pulling environment variables from Supabase...${NC}"
supabase secrets list --linked

# Get project URL and keys
PROJECT_URL=$(supabase status --linked 2>/dev/null | grep "API URL" | awk '{print $3}' || echo "")
ANON_KEY=$(supabase status --linked 2>/dev/null | grep "anon key" | awk '{print $3}' || echo "")
SERVICE_KEY=$(supabase status --linked 2>/dev/null | grep "service_role key" | awk '{print $3}' || echo "")

if [ -z "$PROJECT_URL" ] || [ -z "$ANON_KEY" ]; then
    echo -e "${YELLOW}⚠️  Could not auto-detect credentials${NC}"
    echo "Please get them from: https://app.supabase.com/project/_/settings/api"
    read -p "Supabase Project URL: " PROJECT_URL
    read -p "Anon Key: " ANON_KEY
    read -p "Service Role Key: " SERVICE_KEY
fi

# Update .env.local
ENV_FILE=".env.local"
echo ""
echo -e "${BLUE}Updating .env.local...${NC}"

if [ -f "$ENV_FILE" ]; then
    # Backup existing file
    cp "$ENV_FILE" "${ENV_FILE}.backup.$(date +%Y%m%d_%H%M%S)"
    echo -e "${YELLOW}Backed up existing .env.local${NC}"
fi

# Create/update .env.local
cat > "$ENV_FILE" << EOF
# Supabase Configuration - Cloud (via CLI)
# Generated by setup-supabase-cloud.sh on $(date)

# Supabase Cloud Instance
NEXT_PUBLIC_SUPABASE_URL=${PROJECT_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SERVICE_KEY}

# API Server Configuration
SUPABASE_URL=${PROJECT_URL}
SUPABASE_ANON_KEY=${ANON_KEY}
SUPABASE_SERVICE_KEY=${SERVICE_KEY}
EOF

echo -e "${GREEN}✓ Updated .env.local${NC}"
echo ""

# Ask about migrations
echo -e "${BLUE}Database Migrations${NC}"
echo ""
read -p "Do you want to push migrations to Supabase cloud? (Y/n): " -n 1 -r
echo ""

if [[ ! $REPLY =~ ^[Nn]$ ]]; then
    echo -e "${BLUE}Pushing migrations to Supabase...${NC}"
    echo ""
    
    # Check migration status
    echo "Checking migration status..."
    supabase db remote commit
    
    # Push migrations
    echo ""
    echo "Pushing migrations..."
    supabase db push
    
    if [ $? -eq 0 ]; then
        echo -e "${GREEN}✓ Migrations pushed successfully${NC}"
    else
        echo -e "${YELLOW}⚠️  Migration push had issues. Check the output above.${NC}"
    fi
fi

echo ""
echo -e "${BLUE}╔════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║     Setup Complete                                     ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${GREEN}✓ Supabase Cloud linked${NC}"
echo -e "${GREEN}✓ Environment variables configured${NC}"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo "1. Verify connection: npm run supabase:verify"
echo "2. Check Supabase dashboard: https://app.supabase.com"
echo "3. Start development: npm run dev"
echo ""

